name: Push and Dispatch Reusable Workflow

on:
  workflow_call:
    inputs:
      config-path:
        required: false
    secrets: inherit

jobs:
  validate:
  runs-on: ubuntu-latest
  steps:
    
      # Checkout the relevant content - different for Push & Pull Request
      - name: Checkout For Push or Workflow Dispatch
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v2
        with:
           ref: ${{ github.event.inputs.branch }}
           fetch-depth: 0    
      
      # Setup NodeJS LTS (18 currently)
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install hdoc-tools globally
      - name: Install hdoc-tools
        run: npm install hdoc-tools -g
     
     # Run hdoc build against checked-out content
      - name: Perform Validation
        id: hdocbuild
        run: |
          if result=`hdoc build 2>&1`; then
              printf "Build Success!\n\n"
              printf "$result"
              exit 0
          else
            valout=$(echo "$result" | awk '/Validation Output/,0')
            printf "Build Failed!\n\n-----------------------\n"
            printf "$valout"
            exit 1
          fi
          
      # If build validation is successful, echo message
      - name: Build Success
        if: success()
        run: echo "::notice::Build validation passed successfully."
